name: django-sso-auth

on:
  push:
    branches: [main, staging, development]
  pull_request:
    branches: [main, staging, development]
  workflow_dispatch:

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Setup PDM
        uses: pdm-project/setup-pdm@v4
        with:
          python-version: "3.12"
          cache: true

      - name: Install dependencies
        run: pdm install --dev

      - name: Lint with ruff and black
        run: |
          make lint

      - name: Test with pytest
        run: |
          make test
