name: django-sso-auth

on:
  push:
    branches: [main, staging, development]
  pull_request:
    branches: [main, staging, development]

permissions:
  contents: write

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Setup PDM
        uses: pdm-project/setup-pdm@v4
        with:
          python-version: "3.12"
          cache: true

      - name: Install dependencies
        run: pdm install --dev

      - name: Lint with ruff and black
        run: |
          pdm run lint

      - name: Format with ruff and black
        run: |
          pdm run format

      - name: Test with pytest
        run: |
          pdm run test

  deploy-docs:
    runs-on: ubuntu-latest
    needs: lint-test
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.x

      - name: Cache MkDocs
        uses: actions/cache@v4
        with:
          key: mkdocs-material-${{ github.run_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-

      - name: Install MkDocs and Material theme
        run: pip install mkdocs-material mkdocstrings-python markdown-include pymdown-extensions mkdocs-markdownextradata-plugin mdx-include

      - name: Deploy Documentation to GitHub Pages
        run: mkdocs gh-deploy --force
